import React, { useState, useEffect } from 'react';
import axios from 'axios';
import AICard from '../components/recommendations/AICard';

export default function Challenges() {
  const [recommendations, setRecommendations] = useState([]);
  const [loading, setLoading] = useState(true);
  const [generating, setGenerating] = useState(false);

  useEffect(() => {
    fetchRecommendations();
  }, []);

  const fetchRecommendations = async () => {
    try {
      const userId = localStorage.getItem('user_id');
      if (!userId) {
        setLoading(false);
        return;
      }
      const response = await axios.get(`http://localhost:5000/api/recommendations/${userId}`);
      setRecommendations(response.data);
    } catch (err) {
      console.error("Failed to load recommendations:", err);
    } finally {
      setLoading(false);
    }
  };

  const handleComplete = async (id) => {
    try {
      await axios.put(`http://localhost:5000/api/recommendations/${id}/complete`);
      setRecommendations(prev => prev.filter(r => r.id !== id));
      alert(`Challenge completed! You earned +5 Eco Points.`);
    } catch (err) {
      console.error(err);
      alert("Error completing challenge.");
    }
  };

  const handleGenerate = async () => {
    setGenerating(true);
    try {
      const userId = localStorage.getItem('user_id');
      if (!userId) {
        alert("Please log in first!");
        setGenerating(false);
        return;
      }
      await axios.post('http://localhost:5000/api/recommendations/generate', {
        user_id: parseInt(userId, 10)
      });
      await fetchRecommendations();
    } catch (err) {
      console.error("Generation failed:", err);
      alert("Failed to generate new recommendations.");
    } finally {
      setGenerating(false);
    }
  };

  if (loading) return <div className="p-8">Loading challenges...</div>;

  return (
    <div className="max-w-6xl mx-auto">
      <div className="mb-8 flex justify-between items-end">
        <div>
          <h1 className="text-3xl font-bold text-gray-900">Eco Challenges & AI Recommendations</h1>
          <p className="text-gray-500 mt-1">Complete these personalized tasks generated by Gemini to lower your footprint and boost your Eco Score.</p>
        </div>
        <button 
          onClick={handleGenerate}
          disabled={generating}
          className="py-2 px-6 bg-eco-100 text-eco-700 font-bold rounded-xl hover:bg-eco-200 transition-colors disabled:opacity-50 cursor-pointer"
        >
          {generating ? 'Generating...' : 'Generate New'}
        </button>
      </div>
      
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
        {recommendations.map(rec => (
          <AICard key={rec.id} recommendation={rec} onComplete={handleComplete} />
        ))}
      </div>
      
      {recommendations.length === 0 && (
        <div className="text-center py-12 bg-white rounded-2xl border border-gray-100 shadow-sm mt-6">
          <p className="text-gray-500 mb-4">You've completed all current challenges!</p>
          <button onClick={handleGenerate} disabled={generating} className="py-2 px-6 bg-eco-600 text-white font-bold rounded-xl hover:bg-eco-700 transition-colors disabled:opacity-50 cursor-pointer">
            {generating ? 'Generating...' : 'Get New Recommendations from AI'}
          </button>
        </div>
      )}
    </div>
  );
}
